//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGI.ParkingLot.ConsoleApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressKey { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public bool CurrentAddress { get; set; }
        public int CustomerKey { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
