//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGI.ParkingLot.ConsoleApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KeyCard()
        {
            this.TransactionRecords = new HashSet<TransactionRecord>();
        }
    
        public int KeyCardKey { get; set; }
        public int CustomerKey { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public System.DateTime ActivationDate { get; set; }
        public int KeyCardNumber { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionRecord> TransactionRecords { get; set; }
    }
}
