//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGI.ParkingLot.ConsoleApp.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotHourlyRate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LotHourlyRate()
        {
            this.TransactionRecords = new HashSet<TransactionRecord>();
        }
    
        public int LotHourlyRateKey { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<int> LotKey { get; set; }
        public decimal Rate { get; set; }
    
        public virtual Lot Lot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionRecord> TransactionRecords { get; set; }
    }
}
