//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGI.ParkingLot.ConsoleApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using CGI.ParkingLot.ConsoleApp.Domain;

    public partial class ABCParkingLotEntities : DbContext
    {
        public ABCParkingLotEntities()
            : base("name=ABCParkingLotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresses> Addresses { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<KeyCard> KeyCards { get; set; }
        public virtual DbSet<Lot> Lots { get; set; }
        public virtual DbSet<ParkingSpot> ParkingSpots { get; set; }
        public virtual DbSet<TransactionRecord> TransactionRecords { get; set; }
    }
}
